config/routes.rb
Rails.application.routes.draw do

  get 'teachers/index'

  get 'items_imports/new'

  get 'items_imports/create'

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :courses do     
      resources :events, :controller => "courses_events" do
      post :destroy
      end

  end


  resources :departments

  resources :students do
    resources :contacts
  	collection do
  		get :others
      get :search_auto_complete
      get :search_auto_complete2
      get :search
  	end
  	
    member do
      delete :destroy_courses
    end   

  end

  resources :events
  resources :attendances do
    collection do
      post :create_by_zkteco
    end
  end

  resources :notifies

  namespace :oauth do
    get :index
    post :callback
    post :authorize
    post :send_message
    get '/authorize' => "oauth#get_authorize"
    get '/callback' => "oauth#index"
    get '/send_message' => "oauth#get_send_message"
  end
  namespace :helps do
    get :index
  end

  resources :items
  resources :items_imports, only: [:new, :create]

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student



  # Event.includes(course: :students).where(students:{id:5}).where("start_time > ?", Time.now)
  def self.getAttendance(student)
    self.where("student_id  = ? ", student.id).order("start_time desc")
  end
end

app/models/contact.rb
class Contact < ApplicationRecord

	belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord

	has_many :course_students , :dependent => :destroy
	has_many :students, through: :course_students, :dependent => :destroy
	has_many :events, :dependent => :destroy
end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :course
  belongs_to :student

end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :course
	validates_presence_of :start_time,:end_time
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/items_import.rb
class ItemsImport
    include ActiveModel::Model
    require 'roo'
  
    attr_accessor :file
  
    def initialize(attributes={})
      attributes.each { |name, value| send("#{name}=", value) }
    end
  
    def persisted?
      false
    end
  
    def open_spreadsheet
      case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end
  
    def load_imported_items
      spreadsheet = open_spreadsheet
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).map do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        item = Item.find_by_id(row["id"]) || Item.new
        item.attributes = row.to_hash
        item
      end
    end
  
    def imported_items
      @imported_items ||= load_imported_items
    end
  
    def save
      if imported_items.map(&:valid?).all?
        imported_items.each(&:save!)
        true
      else
        imported_items.each_with_index do |item, index|
          item.errors.full_messages.each do |msg|
            errors.add :base, "Row #{index + 6}: #{msg}"
          end
        end
        false
      end
    end
  
  end

app/models/notify.rb
class Notify < ApplicationRecord
    has_and_belongs_to_many :students
    mount_uploader :image, ImageUploader
end

app/models/student.rb
class Student < ApplicationRecord

	has_many :course_students
	has_many :courses, through: :course_students
	has_and_belongs_to_many :notifies
	has_many :contacts
	accepts_nested_attributes_for :contacts, allow_destroy: true

	scope :studying, -> { joins(:course_students).distinct.order(afts_id: :asc) }
	#scope :studying, -> { includes(:course_students).where.not(course_students:{course_id:nil})}
	scope :others, -> { includes(:course_students).where(course_students:{course_id:nil}).order(afts_id: :asc) }

	def self.term_for(prefix)
		suggestions = where("name like ?", "%#{prefix}%")
	end

	def self.get_next_afts_id()
		now = Time.now
		serial_date = (now.year-1911).to_s + sprintf('%02i', now.mon) + sprintf('%02i', now.day)
		serial_no = "01"
		last_student = Student.order("created_at").last
		if (last_student.nil?)
			return serial_date + serial_no
		end
		last_afts_id = last_student.afts_id
		if (serial_date == last_afts_id[0..6])
			serial_no = sprintf('%02i',last_afts_id[7..8].to_i + 1)
		end
		serial_date + serial_no
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def email_name
	self.email.split("@").first
  end         
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!	

	def index
      @students = Student.studying.page(params[:page] || 1).per(20)
      @destroy_courses_flag = true
	end

	def search_auto_complete
			render json: Student.term_for(params[:term]).limit(10).pluck(:name)
	end


	def search_auto_complete2
			@students = Student.term_for(params[:term])
	end

	def search

	  name = params[:name];
	  render json: Student.where("name like ?", "%#{name}%")

	end	

	def others
      @students = Student.others.page(params[:page] || 1).per(20)
      @destroy_courses_flag = false
	end

	def show
	  @student = Student.find(params[:id])
	end	

	def new
		@student = Student.new
		@student.afts_id = Student.get_next_afts_id
		@courses = Course.all
		2.times { @student.contacts.build }
	end


	def self.new_by_item
		@student = Student.new
		2.times { @student.contacts.build }
		@student
	end

	def create
		puts current_user.id
		tmp_student_params = student_params
		if (Student.get_next_afts_id != tmp_student_params[:afts_id])
			flash[:error] = '學號格式有誤'
			redirect_to action: "new"	
			return
		end
		@student = Student.new(tmp_student_params)
	  # @user = User.new(:email => 'test@example.com', :password => 'password', :password_confirmation => 'password', :name => params[:user][:name])

		@student.user_id = current_user.id
	  if(@student.save)
		  flash[:notice] = '新增學生成功'
		  redirect_to action: "new"	

      else
		  flash[:error] = @student.errors.full_messages
		  render :new
	  end	

	end	

	def edit
		@student = Student.find(params[:id])
		@contacts = Student.first.contacts.all
	end

	def update
	  @student = Student.find(params[:id])
	  

	  if(@student.update(student_params))
			redirect_to students_path
		else
		  flash[:error] = @student.errors.full_messages
		  render :new
	  end		  

	end	

	def destroy_courses
	  @student = Student.find(params[:id])
	  @student.courses.destroy_all

	  redirect_to students_path
	end			

	def destroy
	  @student = Student.find(params[:id])

	  ActiveRecord::Base.transaction do
	    @student.courses.destroy_all
	    @student.destroy
	  end


		redirect_to others_students_url	"pOijrkl"
		
	end

	private

	def student_params
		params.require(:student).permit(:afts_id, :card_id, :school, :grade, :name, :birthday, :identity_code, :address, :remark, :course_ids => [], :contacts_attributes => [:id, :name, :phone, :phone2, :phone3, :notify_demand, :line_token])
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/notify_helper.rb
module NotifyHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_edit.html.erb
<div class="panel-body">
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <%= f.label :name, "學生姓名" %>
          <%= f.text_field :name, class: "form-control"  %>
        </div>    
        <div class="form-group">
          <%= f.label :afts_id, "系統學號" %>
          <%= f.text_field :afts_id, :readonly => true, class: "form-control", :maxlength=>"9"  %>
        </div>
        <div class="form-group">
          <%= f.label :card_id, "學生卡號" %>
          <%= f.text_field :card_id, class: "form-control"  %>
        </div>  
        <div class="form-group">
          <%= f.label :school, "就讀學校" %>
          <%= f.text_field :school, class: "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label :grade, "學生年級" %>
          <%= f.text_field :grade, class: "form-control"  %>
        </div> 
        <div class="form-group">
          <%= f.label :birthday, "生日" %>
          <%= f.date_field :birthday, class: "form-control"  %>
        </div>         
        <div class="form-group">
          <%= f.label :identity_code, "身份證字號" %>
          <%= f.text_field :identity_code, class: "form-control"  %>
        </div>            
        <div class="form-group">
          <%= f.label :address, "住址" %>
          <%= f.text_field :address, class: "form-control"  %>
        </div>         
        <div class="form-group">
          <%= f.label :remark, "備註" %>
          <%= f.text_field :remark, class: "form-control"  %>
        </div>         
        <div class="form-group">
          <%= f.label :courses, "就讀班級" %>
          <%= f.collection_check_boxes(:course_ids, Course.all, :id, :name) do |b| %>
            <div class="checkbox">
              <%= b.label do%>
              <%=b.check_box + b.text%>
              <%end%>
            </div>  
          <% end %>                                      
        </div>
      </div>
      <div class="col-lg-6">
        <%= f.fields_for :contacts do |c| %>
          <div class="form-group">
            <%= c.label :name, "聯絡人姓名" %>
            <%= c.text_field :name, class: "form-control"  %>
          </div>             
          <div class="form-group">
            <%= c.label :phone, "聯絡人電話" %>
            <%= c.text_field :phone, class: "form-control"  %>
          </div>        
          <div class="form-group">
            <%= c.label :phone2, "聯絡人電話二" %>
            <%= c.text_field :phone2, class: "form-control"  %>
          </div>        
          <div class="form-group">
            <%= c.label :phone3, "聯絡人手機" %>
            <%= c.text_field :phone3, class: "form-control"  %>
          </div>  
          <div class="form-group">
            <%= c.label :line_token, "ＬＩＮＥ權杖" %>
            <%= c.text_field :line_token, class: "form-control"  %>
          </div> 
          <div class="form-check">
            <%= c.label :notify_demand, "ＬＩＮＥ通知" %>
            <%= c.check_box :notify_demand%>
          </div>
        <% end %>  
      </div>
    </div>
    <div class="row">
      <div class="text-center"> 
        <%= render 'layouts/messages' %>
      </div>
      <%= link_to "確定", "", class: "btn btn-lg btn-success btn-block", onclick: "addStudent()" %>
    </div>
</div>

app/views/students/_lists.html.erb
<div>
    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
        <div class="row">
            <div class="col-sm-6">
                <div class="dataTables_length" id="dataTables-example_length">
                    <!-- <label>Show <select name="dataTables-example_length" aria-controls="dataTables-example" class="form-control input-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label> -->
                </div>
            </div>
            <div class="col-sm-6">
                <!-- <div id="dataTables-example_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control input-sm" placeholder="" aria-controls="dataTables-example"></label></div> --></div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table width="100%" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                    <thead>
                        <tr role="row">
                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 204px;">學生姓名
                            </th>
                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 250px;">系統學號</th>
                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 228px;">就讀學校</th>
                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 178px;">學生年級</th>
                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 134px;">最後更新日期</th>
                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 134px;"></th>                            
                        </tr>
                    </thead>
                    <tbody>
                        <% students.each do |student| %>
                            <tr>
                                <td>
                                    <%= link_to student.name, edit_student_path(student) %>
                                </td>
                                <td>
                                    <%= student.afts_id  %>
                                </td>
                                <td>
                                    <%= student.school  %>
                                </td>
                                <td>
                                    <%= student.grade  %>
                                </td>
                                <td>
                                    <%= student.updated_at.strftime("%F %T")  %>
                                </td>

                                <td>
                                    <% if @destroy_courses_flag %>
                                        <%= link_to "退班", destroy_courses_student_path(student), method: :delete, class: "btn btn-warning btn-sm", data: {confirm: '移除所有班級，並加入潛在學生，是否繼續？'} %>
                                    <% else %>    
                                        <%= link_to "刪除", student_path(student), method: :delete, class: "btn btn-danger btn-sm", data: {confirm: '移除後將無法復原，確定刪除？'}%>                                   
                                    <% end %>
                                </td>                            
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">
                    <!-- Showing 1 to 10 of 57 entries -->
                </div>
            </div>
            <div class="col-sm-6">
                <div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
                    <%= paginate students %>
                </div>
            </div>
        </div>
    </div>
    <!-- /.table-responsive -->
    <!--                             <div class="well">
                        <h4>DataTables Usage Information</h4>
                        <p>DataTables is a very flexible, advanced tables plugin for jQuery. In SB Admin, we are using a specialized version of DataTables built for Bootstrap 3. We have also customized the table headings to use Font Awesome icons in place of images. For complete documentation on DataTables, visit their website at <a target="_blank" href="https://datatables.net/">https://datatables.net/</a>.</p>
                        <a class="btn btn-default btn-lg btn-block" target="_blank" href="https://datatables.net/">View DataTables Documentation</a>
                    </div> -->
</div>
<!-- /.panel-body -->

app/views/students/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">修改學生</h2>
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          學生資料
        </div>
        <%= form_for @student, url: student_path(@student), method: :patch do |f| %>
          <%= render "students/edit", f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">就讀中學生</h2>
            <%= link_to "潛在學生", others_students_path, style:"position: absolute; left: 180px; top: 50%;" %>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
                <%= render "students/lists", students: @students %>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>

app/views/students/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">新增學生</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          學生資料
        </div>
        <%= form_for @student, url: students_path, method: :post do |f| %>
          <%= render "students/edit", f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/others.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">潛在學生</h2>
            <%= link_to "就讀中學生", students_path, style:"position: absolute; left: 150px; top: 50%;" %>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
                <%= render "students/lists", students: @students %>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>