config/routes.rb
Rails.application.routes.draw do

  get 'teachers/index'

  get 'items_imports/new'

  get 'items_imports/create'

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :courses do     
      resources :events, :controller => "courses_events" do
      post :destroy
      end

  end


  resources :departments

  resources :students do
    resources :contacts
  	collection do
  		get :others
      get :search_auto_complete
      get :search_auto_complete2
      get :search
  	end
  	
    member do
      delete :destroy_courses
    end   

  end

  resources :events
  resources :attendances do
    collection do
      post :create_by_zkteco
    end
  end

  resources :notifies

  namespace :oauth do
    get :index
    post :callback
    post :authorize
    post :send_message
    get '/authorize' => "oauth#get_authorize"
    get '/callback' => "oauth#index"
    get '/send_message' => "oauth#get_send_message"
  end
  namespace :helps do
    get :index
  end

  resources :items
  resources :items_imports, only: [:new, :create]

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student



  # Event.includes(course: :students).where(students:{id:5}).where("start_time > ?", Time.now)
  def self.getAttendance(student)
    self.where("student_id  = ? ", student.id).order("start_time desc")
  end
end

app/models/contact.rb
class Contact < ApplicationRecord

	belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord

	has_many :course_students , :dependent => :destroy
	has_many :students, through: :course_students, :dependent => :destroy
	has_many :events, :dependent => :destroy
end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :course
  belongs_to :student

end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :course
	validates_presence_of :start_time,:end_time
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/items_import.rb
class ItemsImport
    include ActiveModel::Model
    require 'roo'
  
    attr_accessor :file
  
    def initialize(attributes={})
      attributes.each { |name, value| send("#{name}=", value) }
    end
  
    def persisted?
      false
    end
  
    def open_spreadsheet
      case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end
  
    def load_imported_items
      spreadsheet = open_spreadsheet
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).map do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        item = Item.find_by_id(row["id"]) || Item.new
        item.attributes = row.to_hash
        item
      end
    end
  
    def imported_items
      @imported_items ||= load_imported_items
    end
  
    def save
      if imported_items.map(&:valid?).all?
        imported_items.each(&:save!)
        true
      else
        imported_items.each_with_index do |item, index|
          item.errors.full_messages.each do |msg|
            errors.add :base, "Row #{index + 6}: #{msg}"
          end
        end
        false
      end
    end
  
  end

app/models/notify.rb
class Notify < ApplicationRecord
    has_and_belongs_to_many :students
    mount_uploader :image, ImageUploader
end

app/models/student.rb
class Student < ApplicationRecord

	has_many :course_students
	has_many :courses, through: :course_students
	has_and_belongs_to_many :notifies
	has_many :contacts
	accepts_nested_attributes_for :contacts, allow_destroy: true

	scope :studying, -> { joins(:course_students).distinct.order(afts_id: :asc) }
	#scope :studying, -> { includes(:course_students).where.not(course_students:{course_id:nil})}
	scope :others, -> { includes(:course_students).where(course_students:{course_id:nil}).order(afts_id: :asc) }

	def self.term_for(prefix)
		suggestions = where("name like ?", "%#{prefix}%")
	end

	def self.get_next_afts_id()
		now = Time.now
		serial_date = (now.year-1911).to_s + sprintf('%02i', now.mon) + sprintf('%02i', now.day)
		serial_no = "01"
		last_student = Student.order("created_at").last
		if (last_student.nil?)
			return serial_date + serial_no
		end
		last_afts_id = last_student.afts_id
		if (serial_date == last_afts_id[0..6])
			serial_no = sprintf('%02i',last_afts_id[7..8].to_i + 1)
		end
		serial_date + serial_no
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def email_name
	self.email.split("@").first
  end         
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!

	def index
	  @events = Event.all
	  @courses = Course.all
	  @students = Student.all
	end	
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/notify_helper.rb
module NotifyHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<div id="page-wrapper" style="min-height: 708px;">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-users fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">
                                <%= @students.studying.count %>
                            </div>
                            <div>就讀中學生</div>
                        </div>
                    </div>
                </div>
                <%= link_to students_path do %>
                    <div class="panel-footer">
                        <span class="pull-left">詳細內容</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                    <% end %>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">
                                <%= @students.others.count %>
                            </div>
                            <div>潛在學生</div>
                        </div>
                    </div>
                </div>
                <%= link_to others_students_path do %>
                    <div class="panel-footer">
                        <span class="pull-left">詳細內容</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                    <% end %>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-calendar fa-fw"></i> 課表
                    <div class="pull-right">
<!--                         <div class="btn-group">
                            <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                Actions
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li><a href="#">Action</a>
                                </li>
                                <li><a href="#">Another action</a>
                                </li>
                                <li><a href="#">Something else here</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a>
                                </li>
                            </ul>
                        </div> -->
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                   <div class="calendar_home"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> 所有班級
                    <div class="btn-group pull-right">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-chevron-down"></i>
                        </button>
                        <ul class="dropdown-menu slidedown">
                            <li>
                                <a href="/courses/new">
                                    <i class="fa fa-plus fa-fw"></i> 新增班級
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="list-group">
                        <% @courses.each do |c| %>
                            <a href="/courses/<%= c.id %>" class="list-group-item">
                                    <i class="fa fa-bookmark fa-fw"></i> <%= c.name %>
                                </a>
                            <% end %>
                    </div>
                    <!-- /.list-group -->
                    <!-- <a href="#" class="btn btn-default btn-block">View All Alerts</a> -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
            <!-- /.panel -->
            <!-- /.panel .chat-panel -->
        </div>
    </div>
    <!-- /.row -->

    <!-- /.row -->
</div>