config/routes.rb
Rails.application.routes.draw do

  get 'teachers/index'

  get 'items_imports/new'

  get 'items_imports/create'

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :courses do     
      resources :events, :controller => "courses_events" do
      post :destroy
      end

  end


  resources :departments

  resources :students do
    resources :contacts
  	collection do
  		get :others
      get :search_auto_complete
      get :search_auto_complete2
      get :search
  	end
  	
    member do
      delete :destroy_courses
    end   

  end

  resources :events
  resources :attendances do
    collection do
      post :create_by_zkteco
    end
  end

  resources :notifies

  namespace :oauth do
    get :index
    post :callback
    post :authorize
    post :send_message
    get '/authorize' => "oauth#get_authorize"
    get '/callback' => "oauth#index"
    get '/send_message' => "oauth#get_send_message"
  end
  namespace :helps do
    get :index
  end

  resources :items
  resources :items_imports, only: [:new, :create]

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student



  # Event.includes(course: :students).where(students:{id:5}).where("start_time > ?", Time.now)
  def self.getAttendance(student)
    self.where("student_id  = ? ", student.id).order("start_time desc")
  end
end

app/models/contact.rb
class Contact < ApplicationRecord

	belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord

	has_many :course_students , :dependent => :destroy
	has_many :students, through: :course_students, :dependent => :destroy
	has_many :events, :dependent => :destroy
end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :course
  belongs_to :student

end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :course
	validates_presence_of :start_time,:end_time
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/items_import.rb
class ItemsImport
    include ActiveModel::Model
    require 'roo'
  
    attr_accessor :file
  
    def initialize(attributes={})
      attributes.each { |name, value| send("#{name}=", value) }
    end
  
    def persisted?
      false
    end
  
    def open_spreadsheet
      case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end
  
    def load_imported_items
      spreadsheet = open_spreadsheet
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).map do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        item = Item.find_by_id(row["id"]) || Item.new
        item.attributes = row.to_hash
        item
      end
    end
  
    def imported_items
      @imported_items ||= load_imported_items
    end
  
    def save
      if imported_items.map(&:valid?).all?
        imported_items.each(&:save!)
        true
      else
        imported_items.each_with_index do |item, index|
          item.errors.full_messages.each do |msg|
            errors.add :base, "Row #{index + 6}: #{msg}"
          end
        end
        false
      end
    end
  
  end

app/models/notify.rb
class Notify < ApplicationRecord
    has_and_belongs_to_many :students
    mount_uploader :image, ImageUploader
end

app/models/student.rb
class Student < ApplicationRecord

	has_many :course_students
	has_many :courses, through: :course_students
	has_and_belongs_to_many :notifies
	has_many :contacts
	accepts_nested_attributes_for :contacts, allow_destroy: true

	scope :studying, -> { joins(:course_students).distinct.order(afts_id: :asc) }
	#scope :studying, -> { includes(:course_students).where.not(course_students:{course_id:nil})}
	scope :others, -> { includes(:course_students).where(course_students:{course_id:nil}).order(afts_id: :asc) }

	def self.term_for(prefix)
		suggestions = where("name like ?", "%#{prefix}%")
	end

	def self.get_next_afts_id()
		now = Time.now
		serial_date = (now.year-1911).to_s + sprintf('%02i', now.mon) + sprintf('%02i', now.day)
		serial_no = "01"
		last_student = Student.order("created_at").last
		if (last_student.nil?)
			return serial_date + serial_no
		end
		last_afts_id = last_student.afts_id
		if (serial_date == last_afts_id[0..6])
			serial_no = sprintf('%02i',last_afts_id[7..8].to_i + 1)
		end
		serial_date + serial_no
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def email_name
	self.email.split("@").first
  end         
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename='items.xlsx'"
      }
      format.html { render :index }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_student
    @items = Item.all
    @items.each do |i|
      @student = Student.find_by(afts_id: i.afts_id) || Student.find_by(afts_id: Student.get_next_afts_id)
      @s = @student || StudentsController.new_by_item
      @s.afts_id = i.afts_id || Student.get_next_afts_id
      @s.name = i.name
      @s.card_id = i.card_id
      @s.school = i.school
      @s.grade = i.grade
      @s.user_id = 1
      @s.birthday = i.birthday
      @s.identity_code = i.identity_code
      @s.address =  i.address
      @s.remark =  i.remark
      if (!i.contact_name.nil? and i.contact_name != "")
        @c = @s.contacts[1]
        @c.name = i.contact_name
        @c.phone = i.contact_phone
        @c.phone2 = i.contact_phone2
        @c.phone3 = i.contact_phone3
        @c.save
      end
      @s.save
      @s.reload
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/notify_helper.rb
module NotifyHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :item_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>
<%=
  link_to 'Download as Excel',
  items_path(format: :xlsx)
%>

<table>
  <thead>
    <tr>																					
      <th>序號</th>																				
      <th>姓名</th>
      <th>學生卡號(悠遊卡)</th>
      <th>打卡機系統號</th>
      <th>就讀學校</th>
      <th>年級</th>
      <th>身份證號</th>
      <th>生日</th>
      <th>住址</th>
      <th>聯絡人姓名</th>
      <th>聯絡人電話一</th>
      <th>聯絡人電話二</th>
      <th>聯絡人電話三</th>
      <th>備註</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.card_id %></td>
        <td><%= item.afts_id %></td>
        <td><%= item.school %></td>
        <td><%= item.grade %></td>
        <td><%= item.identity_code %></td>
        <td><%= item.birthday %></td>
        <td><%= item.address %></td>
        <td><%= item.contact_name %></td>
        <td><%= item.contact_phone %></td>
        <td><%= item.contact_phone2 %></td>
        <td><%= item.contact_phone3 %></td>
        <td><%= item.remark %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'insert_student', item, method: :update %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>