config/routes.rb
Rails.application.routes.draw do

  get 'teachers/index'

  get 'items_imports/new'

  get 'items_imports/create'

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :courses do     
      resources :events, :controller => "courses_events" do
      post :destroy
      end

  end


  resources :departments

  resources :students do
    resources :contacts
  	collection do
  		get :others
      get :search_auto_complete
      get :search_auto_complete2
      get :search
  	end
  	
    member do
      delete :destroy_courses
    end   

  end

  resources :events
  resources :attendances do
    collection do
      post :create_by_zkteco
    end
  end

  resources :notifies

  namespace :oauth do
    get :index
    post :callback
    post :authorize
    post :send_message
    get '/authorize' => "oauth#get_authorize"
    get '/callback' => "oauth#index"
    get '/send_message' => "oauth#get_send_message"
  end
  namespace :helps do
    get :index
  end

  resources :items
  resources :items_imports, only: [:new, :create]

  root "home#index"
end

app/controllers/courses/events_controller.rb
class Courses::EventsController < ApplicationController
	include RailsTemporaryData::ControllerHelpers

	def create
	  @event = Event.new(event_params)
	  @course = Course.find(params[:course_id])
	  @event.name = @course.name
	  @event.course = @course

	  if(@event.save)

      else
		  flash[:error] = @event.errors.full_messages  
	  end	

	  redirect_to course_path(params[:course_id])

	end	

	def temp
	  @event = Event.new(event_params)

	  # @events = []

	  # @events.push(@event)
	  if !session[:events]
	  	session[:events] = []
	  end

	  session[:events] << @event
	  session[:name] = params[:event][:name]


	  # uuid = UUIDTools::UUID.timestamp_create().to_s

	  # set_tmp_data(uuid, { start_time: @event.start_time, end_time: @event.end_time})

	  # @course = Course.find(params[:course_id])
	  # @event.name = @course.name
	  # @event.course = @course

	  # if(@event.save)

   #    else
		 #  flash[:error] = @event.errors.full_messages  
	  # end	
	  redirect_to new_course_path
	end		
	

	def new
		@event = Event.new
	end



	private
	def event_params
		params.require(:event).permit(:name, :start_time, :end_time)
	end	

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	include RailsTemporaryData::ControllerHelpers
	before_action :authenticate_user!

	def new
	  # @events = []
	  # @event = Event.new
	  @course = Course.new
	  @students = []
	  @title = "新增班級"
	  # @event_expanded = false
	  
	  # if session[:events]
	  # 	  @course.name = session[:name]

	  # 	  session[:events].each do|e|
	  # 	  	event = Event.new
	  # 	    event.start_time = e["start_time"]
	  # 	    event.end_time = e["end_time"]	  

	  # 	    @events << event
	  # 	  end	

	  # 	  @course.events = @events
	  #     @event_expanded = true
	  # end	


	end	

	def show
	  @course = Course.find(params[:id])
	  @events = Event.where(course_id: @course.id)
	  @event = Event.new
	  @students = @course.students.page(params[:page]).per(20)	  
	end		


	def edit
	  @course = Course.find(params[:id])
	  @students = @course.students
	  @title = "編輯班級"
	end	

	def update
	  @course = Course.find(params[:id])
		@course.name = course_params[:name]
		@course.description = course_params[:description]
	  students = []

		if (!params["students"].nil?)
			params["students"].each do |s|
			student = Student.find(s[:student][:id])

			students <<  student
			end
			@course.students = students
		end
		
	  @course.save!

	  redirect_to course_path(@course)
	  # if(@course.save)
		 #  flash[:notice] = '編輯班級成功'
		 #  redirect_to course_path(@course)

   #    else
		 #  flash[:error] = @course.errors.full_messages
		 #  render :new
	  # end	
	end	
	

	def create
		@course = Course.new(course_params)

	  students = []
		if (!params["students"].nil?)
			params["students"].each do |s|
			student = Student.find(s[:student][:id])

			students <<  student
			end
			@course.students = students
		end

	  @course.save!  

	  redirect_to course_path(@course)


	end	

	def event_new
	  @event = Event.new
	  render "courses/show"
	end	

	private

	def course_params
		params.require(:course).permit(:name, :description)
	end		

	def event_params(event_params)
		event_params.require(:event).permit(:name, :start_time, :end_time)
	end	

end

app/helpers/courses/events_helper.rb
module Courses::EventsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_add_students.html.erb
<div class="modal fade" id="addStudentsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="panel-info">
        <div class="panel-heading">
            請選擇上課學生
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="panel-body" style="min-height: 300px">
            <div class="form-group input-group">
                <input id="students_autocomplete" type="text" class="form-control" placeholder="學生姓名">
                <span class="input-group-btn">
                <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>


            </div>
            <div class="form-group input-group">
                                         <table width="100%" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                                            <thead>
                                                <tr role="row">
                                                    <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 204px;">學生姓名
                                                    </th>
                                                    <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 250px;">系統學號</th>
                                                    <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 228px;">就讀學校</th>
                                                    <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 178px;">學生年級</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <% @students.each do |student| %>
                                                    <tr>
                                                        <td>
                                                            <%= student.name  %>
                                                        </td>
                                                        <td>
                                                            <%= student.afts_id  %>
                                                        </td>
                                                        <td>
                                                            <%= student.school  %>
                                                        </td>
                                                        <td>
                                                            <%= student.grade  %>
                                                        </td>
                                                    </tr>
                                                    <% end %>
                                            </tbody>
                                        </table>               
            </div>           
        </div>
    </div>
</div>

app/views/courses/_datepicker.html.erb
<div class="modal fade" id="addEventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="panel-info">
        <div class="panel-heading">
            請選擇上課時間
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="panel-body" style="min-height: 300px">
            <div class='col-md-5'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker'>
                        <input type='text' class="form-control" />
                        <span class="input-group-addon">
	                      <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class='col-md-1' style="padding: 0px; width: 1%;">-</div>
            <div class='col-md-5'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker2'>
                        <input type='text' class="form-control" />
                        <span class="input-group-addon">
	                      <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <%= form_for @event, url: courses_events_path(course_id: @course.id) do |f| %>
            <%= f.hidden_field  :start_time, type: "hidden"  %>
                <%= f.hidden_field  :end_time, type: "hidden"  %>
                    <div class="panel-footer">
                        <button id="buttonAdd" type="submit" class="btn btn-success">確定</button>
                        <!-- <button id="buttonCancel" type="button" class="btn btn-warning">取消</button> -->
                    </div>
                    <% end %>


    </div>
</div>

app/views/courses/_datepicker2.html.erb
<div class="modal fade" id="addEventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="panel-info">
        <div class="panel-heading">
            請選擇上課時間
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>         
        </div>
        <div class="panel-body" style="min-height: 300px">
            <%= render 'event', event: @event %>
        </div>
        <input type="hidden" name="event[start_time]" id="event_start_time">
        <input type="hidden" name="event[end_time]" id="event_end_time">
        <input type="hidden" name="event[color]" id="event_color">
        <div class="panel-footer">
            <button id="buttonAdd" data-actiontype="edit" type="button" class="btn btn-success">確定</button>
            <button id="buttonCancel" type="button" class="btn btn-warning">取消</button>
        </div>
    </div>
</div>

app/views/courses/_datepicker3.html.erb
<div class="modal fade" id="updateEventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
    <div class="panel-info">
        <div class="panel-heading">
            請選擇上課時間
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>         
        </div>
        <div class="panel-body" style="min-height: 300px">
            <%= render 'event', event: @event %>
        </div>
        <input type="hidden" name="event[start_time]" id="event_start_time">
        <input type="hidden" name="event[end_time]" id="event_end_time">
        <input type="hidden" name="event[color]" id="event_color">
        <input type="hidden" name="event[id]" id="event_id">
        <input type="hidden" name="event[update_url]" id="event_update_url">
        <div class="panel-footer">
            <button id="buttonAdd" type="button" class="btn btn-success">確定</button>
            <button id="buttonCancel" type="button" class="btn btn-warning">取消</button>
            <button id="buttonDestory" type="button" class="btn btn-danger">移除</button>
        </div>
    </div>
</div>

app/views/courses/_editor.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header"><%= @title %></h2>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    班級資料
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="form-group">
                        <%= f.label :name, "班級名稱" %>
                            <%= f.text_field :name, class: "form-control"  %>
                                <%= f.label :description, "說明" %>
                                    <%= f.text_field :description, class: "form-control"  %>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    就讀學生
                </div>
                <div class="panel-body">
                    <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                未加入
                            </div>
                            <div class="panel-body">
                                <div class="form-group input-group">
                                    <input id="input_students_autocomplete" type="text" class="form-control" placeholder="學生姓名">
                                    <span class="input-group-btn">
                                        <button id="button_search_student" class="btn btn-default" type="button"><i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                                <table width="100%" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-students" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 204px;">學生姓名
                                            </th>
                                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 178px;">學生年級</th>
                                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" "></th>                                                        
                                        </tr>
                                    </thead>
                                    <tbody>                                                  
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                已加入
                            </div>
                            <div class="panel-body">
                                <table width="100%"  class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-students-added" role="grid " aria-describedby="dataTables-example_info" style="width: 100%; ">
                                    <thead>
                                        <tr role="row ">
                                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending " aria-label="Rendering engine: activate to sort column descending  style="width: 204px; ">學生姓名
                                            </th>
                                            <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending " style="width: 178px; ">學生年級</th>
                                                <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @students.each do |student| %>
                                            <%= fields_for 'students[]student', student do |p| %>
                                                <tr>
                                                    <td>
                                                        <%= link_to student.name, edit_student_path(student) %>
                                                    </td>
                                                    <td>
                                                        <%= student.afts_id  %>
                                                    </td>
                                                    <td>
                                                        <a class="remove_student" href="<%= student.id %>">
                                                            <button type="button" class="btn btn-primary btn-xs" onclick="$(this).closest('tr').remove(); return false">移出</button>
                                                        </a>
                                                        <%= p.hidden_field :id %>
                                                    </td>
                                                </tr>
                                            <% end %>
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <%= link_to "確定", "", class: "btn btn-lg btn-success btn-block", onclick: "$('form').submit();return false" %>
            </div>
        </div>
    </div>
</div>

app/views/courses/_event.html.erb
<div class="row">
    <div class="col-md-2"><h4>日期</h4></div>
    <div class="col-md-5">
    <div class="form-group">
        <input type='text' class="form-control start_date" readonly/>
    </div>
    </div>
</div>
<div class="row">
    <div class='col-md-2'>
        <h4>開始</h4>
    </div>
    <div class='col-md-5'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker'>
                <input type='text' class="form-control start" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>  
        </div>
    </div>
</div>
<div class="row">
    <div class='col-md-2'>
        <h4>結束</h4>
    </div>
    <div class='col-md-5'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker2'>
                <input type='text' class="form-control end" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>  
        </div>        
    </div>           
</div>
<div class="row">
    <div class='col-md-2'>
        <h4>識別</h4>
    </div>
    <div class='col-md-5'>
        <div class="form-group" style="padding-top:2px">
        <select id="colorselector">
            <option value="1" data-color="#FF0000" selected="selected">red</option>
            <option value="2" data-color="#FF8C00">darkorange</option>
            <option value="5" data-color="#FFD700">gold</option>
            <option value="3" data-color="#32CD32">limegreen</option>
            <option value="4" data-color="#6495ED">cornflowerblue</option>
        </select>
        <input type="text" id="colorValue" class="hidden"/>
        <input type="text" id="colorColor" class="hidden" />
        <input type="text" id="colorTitle" class="hidden" />
        </div>        
    </div>           
</div>

app/views/courses/edit.html.erb
<%= form_for @course, url: course_path(@course), method: :patch do |f| %>
    <%= render 'courses/editor', f: f %>
<% end %>

app/views/courses/new.html.erb
<%= form_for @course, url: courses_path, method: :post do |f| %>
    <%= render 'courses/editor', f: f %>
<% end %>

app/views/courses/show.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><%=@course.name%></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <%=@course.name%>
                        <div class="pull-right">
                            <a href="/courses/<%= @course.id %>/edit">
                                <button type="button" class="btn btn-primary btn-xs">編輯</button>
                            </a>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="#">畢業</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#home" data-toggle="tab">課表</a>
                        </li>
                        <li><a href="#profile" data-toggle="tab">就讀中學生</a>
                        </li>
                        <!--                         <li><a href="#messages" data-toggle="tab">Messages</a>
                        </li>
                        <li><a href="#settings" data-toggle="tab">Settings</a>
                        </li> -->
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="home">
                            <div id="calendar"></div>
                        </div>
                        <div class="tab-pane fade" id="profile">
                            <h4></h4>
                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="dataTables_length" id="dataTables-example_length">
                                            <!-- <label>Show <select name="dataTables-example_length" aria-controls="dataTables-example" class="form-control input-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label> -->
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <!-- <div id="dataTables-example_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control input-sm" placeholder="" aria-controls="dataTables-example"></label></div> --></div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table width="100%" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                                            <button id="button_add_students" type="button" class="btn btn-primary">加入學生</button>
                                            <thead>
                                                <tr role="row">
                                                    <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 204px;">學生姓名
                                                    </th>
                                                    <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 250px;">系統學號</th>
                                                    <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 228px;">就讀學校</th>
                                                    <th class="" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 178px;">學生年級</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <% @students.each do |student| %>
                                                    <tr>
                                                        <td>
                                                            <%= link_to student.name, edit_student_path(student) %>
                                                        </td>
                                                        <td>
                                                            <%= student.afts_id  %>
                                                        </td>
                                                        <td>
                                                            <%= student.school  %>
                                                        </td>
                                                        <td>
                                                            <%= student.grade  %>
                                                        </td>
                                                    </tr>
                                                <% end %>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">
                                            <!-- Showing 1 to 10 of 57 entries -->
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
                                            <%= paginate @students%>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="messages">
                            <h4>Messages Tab</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                        </div>
                        <div class="tab-pane fade" id="settings">
                            <h4>Settings Tab</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                        </div>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<%= render 'courses/datepicker2' %>
<%= render 'courses/datepicker3' %>
<%= render 'courses/add_students' %>